//! The fixture suite (DESIGN §14).
//!
//! Every other test in this crate runs on values or on bytes it built itself.
//! These run on real containers -- generated by ffmpeg at test time, a few
//! kilobytes each, never checked in and never anyone's media. That is the
//! difference that matters: the write path's guarantees are claims about what
//! ffmpeg, exiftool and the container actually do, and nothing but a real file
//! can check them.
//!
//! Ordered as §14 orders them, by what they would have caught. The first is
//! the XMP regression: the data loss the whole write path is shaped around.
//!
//! These need `ffmpeg` and `exiftool` on PATH, which the tool needs anyway.
//! They are ordinary `cargo test` tests, not `#[ignore]`d ones -- a suite that
//! has to be remembered is a suite that does not run.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::model::value::Value;
use crate::tags::plan::{self, Writer};
use crate::tags::probe::{self, FileTags};
use crate::tags::write;

/// A directory of this test's own, so tests that mutate their fixtures cannot
/// collide with each other under `cargo test`'s thread pool.
fn workspace(test: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("tagform-fixtures-{}/{test}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("making the fixture directory");
    dir
}

/// One second of colour bars and a tone, in whatever container and with
/// whatever tags the caller asks for. About 16 KB.
fn generate(dir: &Path, name: &str, args: &[&str]) -> PathBuf {
    let path = dir.join(name);
    let mut cmd = Command::new("ffmpeg");
    cmd.args(["-hide_banner", "-loglevel", "error", "-nostdin", "-y"])
        .args(["-f", "lavfi", "-i", "testsrc=d=1:s=160x120"])
        .args(["-f", "lavfi", "-i", "sine=d=1"])
        .args(["-c:v", "libx264", "-c:a", "aac"])
        .args(args)
        .arg("--")
        .arg(&path);
    let out = cmd.output().expect("ffmpeg must be on PATH to run the fixture suite");
    assert!(
        out.status.success(),
        "generating {name}: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    path
}

/// The ordinary case: an mdta-tagged file, moov at the end, as ffmpeg leaves it.
fn tagged(dir: &Path, name: &str) -> PathBuf {
    generate(
        dir,
        name,
        &[
            "-movflags",
            "+use_metadata_tags",
            "-metadata",
            "title=Original",
            "-metadata",
            "category=Footage",
            "-metadata",
            "keywords=a, b",
        ],
    )
}

fn exiftool(args: &[&str]) {
    let cfg = concat!(env!("CARGO_MANIFEST_DIR"), "/assets/tagform.exiftool.cfg");
    let out = Command::new("exiftool")
        .args(["-config", cfg, "-q", "-overwrite_original_in_place"])
        .args(args)
        .output()
        .expect("exiftool must be on PATH to run the fixture suite");
    assert!(out.status.success(), "exiftool: {}", String::from_utf8_lossy(&out.stderr));
}

fn staged(pairs: &[(&str, &str)]) -> BTreeMap<String, Value> {
    pairs
        .iter()
        .map(|(k, v)| (k.to_string(), Value::Text(v.to_string())))
        .collect()
}

/// Plan and execute, the way the form does.
fn write_it(path: &Path, edits: &BTreeMap<String, Value>, faststart: bool) -> (Writer, Result<(), String>) {
    let tags = probe::probe(path).expect("probing the fixture");
    let plan = plan::build(&tags, edits, faststart);
    let mut on = |_: write::Step| {};
    let r = write::execute(&plan, &tags.xmp, &mut on).map_err(|e| e.to_string());
    (plan.writer, r)
}

fn text(t: &FileTags, key: &str) -> Option<String> {
    t.atoms.get(key).map(|v| match v {
        Value::Text(s) => s.clone(),
        Value::List(l) => l.join(", "),
    })
}

// ---------------------------------------------------------------------------
// the XMP regression -- §2.2, and the reason the write path has its shape
// ---------------------------------------------------------------------------

/// Write XMP with exiftool, then run a `tagform` write over it, and assert
/// every field is still there. An ffmpeg remux destroys all of this silently,
/// so this test failing means the tool is eating `rename-footage`'s data.
#[test]
fn every_xmp_field_survives_a_write() {
    let dir = workspace("xmp-survives");
    let f = tagged(&dir, "xmp.mp4");
    let p = f.to_string_lossy().into_owned();
    exiftool(&[
        "-XMP-dc:Subject=tag1",
        "-XMP-dc:Subject=tag2",
        "-XMP-iptcExt:PersonInImage=Person One",
        "-xmp:Rating=4",
        "-XMP-xmpMM:PreservedFileName=IMG_0001.MOV",
        "--",
        &p,
    ]);
    // Four tags, not five: the two Subject values are one list.
    let before = probe::probe(&f).unwrap().xmp;
    assert_eq!(before.len(), 4, "the fixture must carry XMP to be worth testing");

    // A key the file does not have, so this cannot take the cheap in-place path.
    let (writer, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    r.expect("the write must succeed");
    assert_ne!(writer, Writer::Exiftool, "the fixture was meant to force a rewrite");

    let after = probe::probe(&f).unwrap().xmp;
    assert_eq!(after, before, "XMP changed across a write");
    assert_eq!(text(&probe::probe(&f).unwrap(), "origin"), Some("Camera".into()));
}

/// The rule §9.2 encodes: a file carrying XMP must never be handed to a bare
/// ffmpeg remux, whatever else is true of it.
#[test]
fn a_file_carrying_xmp_never_routes_to_a_bare_remux() {
    let dir = workspace("xmp-routing");
    let f = tagged(&dir, "xmp.mp4");
    exiftool(&["-xmp:Rating=4", "--", &f.to_string_lossy()]);

    for edits in [
        staged(&[("title", "Updated")]),     // update only
        staged(&[("origin", "Camera")]),     // adds a key
    ] {
        let tags = probe::probe(&f).unwrap();
        for faststart in [false, true] {
            let plan = plan::build(&tags, &edits, faststart);
            assert_ne!(
                plan.writer,
                Writer::Ffmpeg,
                "a bare remux would destroy this file's XMP (why: {})",
                plan.why
            );
        }
    }
}

// ---------------------------------------------------------------------------
// round-trips
// ---------------------------------------------------------------------------

/// Write every field the schema claims, read it back through both readers.
/// This is what turns the mapping table into something checked rather than
/// assumed -- a key ffmpeg or exiftool silently drops fails here.
#[test]
fn every_field_round_trips() {
    let dir = workspace("round-trip");
    let f = tagged(&dir, "all.mp4");

    // One field per container key. `actors` and `artist` both write `artist`
    // (DESIGN §17.4), and staging both would be asking for two values in one
    // key -- which is its own test, below.
    let mut claimed: Vec<&str> = Vec::new();
    let mut edits: BTreeMap<String, Value> = BTreeMap::new();
    let mut fields: Vec<&crate::model::schema::FieldDef> = Vec::new();
    for def in crate::model::schema::FIELDS.iter().filter(|d| !d.mdta.is_empty()) {
        if def.mdta.iter().any(|k| claimed.contains(k)) {
            continue;
        }
        claimed.extend(def.mdta.iter().copied());
        edits.insert(def.id.to_string(), Value::Text(format!("v-{}", def.id)));
        fields.push(def);
    }
    assert!(edits.len() > 10, "the schema should have plenty of mdta-backed fields");

    let (_, r) = write_it(&f, &edits, false);
    r.expect("the write must succeed");

    let got = probe::probe(&f).unwrap();
    let mut missing: Vec<String> = Vec::new();
    for def in fields {
        let want = format!("v-{}", def.id);
        for key in def.mdta {
            if text(&got, key).as_deref() != Some(want.as_str()) {
                missing.push(format!("{key} = {:?}, wanted {want:?}", text(&got, key)));
            }
        }
    }
    assert!(missing.is_empty(), "keys did not round-trip:\n  {}", missing.join("\n  "));
}

/// An emptied field must remove the key, not leave an empty one behind: an
/// empty string reads back as a present-but-blank value and shows in the form
/// as an edit that did nothing.
#[test]
fn an_emptied_field_removes_the_key() {
    let dir = workspace("delete");
    let f = tagged(&dir, "del.mp4");
    assert_eq!(text(&probe::probe(&f).unwrap(), "title"), Some("Original".into()));

    let (_, r) = write_it(&f, &staged(&[("title", "")]), false);
    r.expect("the write must succeed");

    let got = probe::probe(&f).unwrap();
    assert_eq!(text(&got, "title"), None, "the key should be gone, not empty");
    assert_eq!(text(&got, "category"), Some("Footage".into()), "a neighbour was lost");
}

/// Unrecognised keys are never dropped (invariant 4): a key no field claims
/// has to survive a write aimed at a different field.
#[test]
fn a_key_no_field_claims_survives() {
    let dir = workspace("custom-key");
    let f = generate(
        &dir,
        "custom.mp4",
        &["-movflags", "+use_metadata_tags", "-metadata", "title=Original", "-metadata", "sound_designer=Someone"],
    );
    let (_, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    r.expect("the write must succeed");
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "sound_designer"),
        Some("Someone".into()),
        "a key the schema does not know was dropped"
    );
}

/// Two fields, one container key: `actors` and `artist` both write `artist`
/// (DESIGN §17.4). Setting them to different values cannot be honoured, and
/// what matters is that it **fails** rather than silently keeping whichever
/// value the plan happened to sort last.
///
/// Pinned rather than endorsed: if §17.4 is ever answered by making Artist
/// mirror Actors, this test is the one that should change.
#[test]
fn two_fields_writing_one_key_fail_rather_than_pick_a_winner() {
    let dir = workspace("collision");
    let f = tagged(&dir, "collide.mp4");
    let before = std::fs::read(&f).unwrap();

    let (_, r) = write_it(&f, &staged(&[("actors", "One, Two"), ("artist", "Someone Else")]), false);

    assert!(r.is_err(), "two values for one key must not report success");
    assert!(
        r.unwrap_err().contains("did not round-trip"),
        "the verify is what catches this, and its message is what explains it"
    );
    assert_eq!(std::fs::read(&f).unwrap(), before, "a failed write changed the file");
}

// ---------------------------------------------------------------------------
// tracks and layout
// ---------------------------------------------------------------------------

/// A second audio track and a timecode track both survive. The timecode track
/// is the one that made an early remux fail outright, and the second audio
/// track is the one a careless `-map 0:a` would silently drop.
#[test]
fn extra_tracks_survive_a_write() {
    let dir = workspace("tracks");
    let f = dir.join("two.mp4");
    let out = Command::new("ffmpeg")
        .args(["-hide_banner", "-loglevel", "error", "-nostdin", "-y"])
        .args(["-f", "lavfi", "-i", "testsrc=d=1:s=160x120"])
        .args(["-f", "lavfi", "-i", "sine=d=1"])
        .args(["-f", "lavfi", "-i", "sine=frequency=800:d=1"])
        .args(["-map", "0:v", "-map", "1:a", "-map", "2:a"])
        .args(["-c:v", "libx264", "-c:a", "aac"])
        .args(["-timecode", "01:00:00:00"])
        .args(["-movflags", "+use_metadata_tags", "-metadata", "title=Original"])
        .arg("--")
        .arg(&f)
        .output()
        .expect("ffmpeg");
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));

    let before = write::probe_streams(&f);
    assert_eq!(before.len(), 4, "video, two audio, timecode");

    let (_, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    r.expect("the write must succeed");
    assert_eq!(write::probe_streams(&f), before, "a track changed across the write");
}

/// A moov-at-end file is detected as such, and asking for faststart moves it.
#[test]
fn a_moov_at_end_file_is_detected_and_moved() {
    use crate::tags::atoms::{layout, Layout};
    let dir = workspace("faststart");
    let f = tagged(&dir, "slow.mp4");
    assert_eq!(layout(&f), Layout::MoovAtEnd, "ffmpeg's default should put moov last");

    let (_, r) = write_it(&f, &staged(&[("title", "Updated")]), true);
    r.expect("the write must succeed");
    assert!(layout(&f).is_faststart(), "faststart was asked for and not delivered");
    assert_eq!(text(&probe::probe(&f).unwrap(), "title"), Some("Updated".into()));
}

/// A fragmented file is declined by the native writer rather than written with
/// offsets it cannot remap. Whether ffmpeg then manages it is a separate
/// question; what matters here is that the native path does not try.
#[test]
fn a_fragmented_file_is_declined_by_the_native_writer() {
    let dir = workspace("fragmented");
    let f = generate(
        &dir,
        "frag.mp4",
        &["-movflags", "+use_metadata_tags+frag_keyframe+empty_moov", "-metadata", "title=Original"],
    );
    assert!(
        crate::tags::native::survey(&f).unwrap().is_none(),
        "a fragmented file must be declined"
    );

    let tags = probe::probe(&f).unwrap();
    let plan = plan::build(&tags, &staged(&[("origin", "Camera")]), false);
    assert_ne!(plan.writer, Writer::Native, "routed to a writer that cannot handle it");
}

// ---------------------------------------------------------------------------
// failure paths -- what matters is that the original is left alone
// ---------------------------------------------------------------------------

/// A file that cannot be replaced fails, and fails without damage. This is the
/// invariant the whole write path exists to keep: a failed write leaves the
/// original exactly as it was.
#[test]
fn a_read_only_directory_fails_and_leaves_the_original_alone() {
    use std::os::unix::fs::PermissionsExt;
    let dir = workspace("read-only");
    let f = tagged(&dir, "ro.mp4");
    let before = std::fs::read(&f).unwrap();

    let mut perms = std::fs::metadata(&dir).unwrap().permissions();
    perms.set_mode(0o500); // r-x: the file cannot be replaced
    std::fs::set_permissions(&dir, perms).unwrap();

    let (_, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);

    let mut perms = std::fs::metadata(&dir).unwrap().permissions();
    perms.set_mode(0o700);
    std::fs::set_permissions(&dir, perms).unwrap();

    assert!(r.is_err(), "a write into a read-only directory must fail");
    assert_eq!(std::fs::read(&f).unwrap(), before, "the original was modified by a failed write");
}

/// A truncated file is not a container. Every path must refuse it rather than
/// produce a plausible-looking result from half an atom chain.
#[test]
fn a_truncated_file_is_refused() {
    let dir = workspace("truncated");
    let f = tagged(&dir, "cut.mp4");
    let whole = std::fs::read(&f).unwrap();
    std::fs::write(&f, &whole[..whole.len() / 2]).unwrap();
    let before = std::fs::read(&f).unwrap();

    // Probing may fail outright, which is a refusal too.
    if let Ok(tags) = probe::probe(&f) {
        let plan = plan::build(&tags, &staged(&[("origin", "Camera")]), false);
        let mut on = |_: write::Step| {};
        assert!(
            write::execute(&plan, &tags.xmp, &mut on).is_err(),
            "a truncated file must not write successfully"
        );
    }
    assert_eq!(std::fs::read(&f).unwrap(), before, "a refused write still changed the file");
}
