//! The fixture suite (DESIGN §14).
//!
//! Every other test in this crate runs on values or on bytes it built itself.
//! These run on real containers -- generated by ffmpeg at test time, a few
//! kilobytes each, never checked in and never anyone's media. That is the
//! difference that matters: the write path's guarantees are claims about what
//! ffmpeg, exiftool and the container actually do, and nothing but a real file
//! can check them.
//!
//! Ordered as §14 orders them, by what they would have caught. The first is
//! the XMP regression: the data loss the whole write path is shaped around.
//!
//! These need `ffmpeg` and `exiftool` on PATH, which the tool needs anyway.
//! They are ordinary `cargo test` tests, not `#[ignore]`d ones -- a suite that
//! has to be remembered is a suite that does not run.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::model::schema::field_by_id;
use crate::model::value::Value;
use crate::tags::atoms;
use crate::tags::plan::{self, Writer};
use crate::tags::probe::{self, FileTags};
use crate::tags::write;

/// A directory of this test's own, so tests that mutate their fixtures cannot
/// collide with each other under `cargo test`'s thread pool.
fn workspace(test: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("tagform-fixtures-{}/{test}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("making the fixture directory");
    dir
}

/// One second of colour bars and a tone, in whatever container and with
/// whatever tags the caller asks for. About 16 KB.
fn generate(dir: &Path, name: &str, args: &[&str]) -> PathBuf {
    let path = dir.join(name);
    let mut cmd = Command::new("ffmpeg");
    cmd.args(["-hide_banner", "-loglevel", "error", "-nostdin", "-y"])
        .args(["-f", "lavfi", "-i", "testsrc=d=1:s=160x120"])
        .args(["-f", "lavfi", "-i", "sine=d=1"])
        .args(["-c:v", "libx264", "-c:a", "aac"])
        .args(args)
        .arg("--")
        .arg(&path);
    let out = cmd
        .output()
        .expect("ffmpeg must be on PATH to run the fixture suite");
    assert!(
        out.status.success(),
        "generating {name}: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    path
}

/// The ordinary case: an mdta-tagged file, moov at the end, as ffmpeg leaves it.
fn tagged(dir: &Path, name: &str) -> PathBuf {
    generate(
        dir,
        name,
        &[
            "-movflags",
            "+use_metadata_tags",
            "-metadata",
            "title=Original",
            "-metadata",
            "category=Footage",
            "-metadata",
            "keywords=a, b",
        ],
    )
}

fn exiftool(args: &[&str]) {
    let cfg = concat!(env!("CARGO_MANIFEST_DIR"), "/assets/tagform.exiftool.cfg");
    let out = Command::new("exiftool")
        .args(["-config", cfg, "-q", "-overwrite_original_in_place"])
        .args(args)
        .output()
        .expect("exiftool must be on PATH to run the fixture suite");
    assert!(
        out.status.success(),
        "exiftool: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

fn staged(pairs: &[(&str, &str)]) -> BTreeMap<String, Value> {
    pairs
        .iter()
        .map(|(k, v)| (k.to_string(), Value::Text(v.to_string())))
        .collect()
}

/// Plan and execute, the way the form does.
fn write_it(
    path: &Path,
    edits: &BTreeMap<String, Value>,
    faststart: bool,
) -> (Writer, Result<(), String>) {
    let tags = probe::probe(path).expect("probing the fixture");
    let plan = plan::build(&tags, edits, faststart);
    let mut on = |_: write::Step| {};
    let r = write::execute(&plan, &tags.xmp, &mut on).map_err(|e| e.to_string());
    (plan.writer, r)
}

/// Probed names are lower-cased; a key is asked for in the case it is written.
fn text(t: &FileTags, key: &str) -> Option<String> {
    t.atoms.get(&key.to_ascii_lowercase()).map(|v| match v {
        Value::Text(s) => s.clone(),
        Value::List(l) => l.join(", "),
    })
}

// ---------------------------------------------------------------------------
// the XMP regression -- §2.2, and the reason the write path has its shape
// ---------------------------------------------------------------------------

/// Write XMP with exiftool, then run a `tagform` write over it, and assert
/// every field is still there. An ffmpeg remux destroys all of this silently,
/// so this test failing means the tool is eating `rename-footage`'s data.
#[test]
fn every_xmp_field_survives_a_write() {
    let dir = workspace("xmp-survives");
    let f = tagged(&dir, "xmp.mp4");
    let p = f.to_string_lossy().into_owned();
    exiftool(&[
        "-XMP-dc:Subject=tag1",
        "-XMP-dc:Subject=tag2",
        "-XMP-iptcExt:PersonInImage=Person One",
        "-xmp:Rating=4",
        "-XMP-xmpMM:PreservedFileName=IMG_0001.MOV",
        "--",
        &p,
    ]);
    // Four tags, not five: the two Subject values are one list.
    let before = probe::probe(&f).unwrap().xmp;
    assert_eq!(
        before.len(),
        4,
        "the fixture must carry XMP to be worth testing"
    );

    // A key the file does not have, so this cannot take the cheap in-place path.
    let (writer, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    r.expect("the write must succeed");
    assert_ne!(
        writer,
        Writer::Exiftool,
        "the fixture was meant to force a rewrite"
    );

    let after = probe::probe(&f).unwrap().xmp;
    assert_eq!(after, before, "XMP changed across a write");
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "origin"),
        Some("Camera".into())
    );
}

/// The rule §9.2 encodes: a file carrying XMP must never be handed to a bare
/// ffmpeg remux, whatever else is true of it.
#[test]
fn a_file_carrying_xmp_never_routes_to_a_bare_remux() {
    let dir = workspace("xmp-routing");
    let f = tagged(&dir, "xmp.mp4");
    exiftool(&["-xmp:Rating=4", "--", &f.to_string_lossy()]);

    for edits in [
        staged(&[("title", "Updated")]), // update only
        staged(&[("origin", "Camera")]), // adds a key
    ] {
        let tags = probe::probe(&f).unwrap();
        for faststart in [false, true] {
            let plan = plan::build(&tags, &edits, faststart);
            assert_ne!(
                plan.writer,
                Writer::Ffmpeg,
                "a bare remux would destroy this file's XMP (why: {})",
                plan.why
            );
        }
    }
}

/// The other side of the same rule: a file with *no* XMP, handed a plan that
/// writes some. A bare remux writes atoms only, so a place typed on a plain
/// download used to be reported written and then read back as nothing. Found
/// by `tagform clone`, whose targets are all fresh ffmpeg output.
#[test]
fn xmp_written_to_a_file_without_any_is_not_dropped() {
    let dir = workspace("xmp-onto-plain");
    // ffmpeg's default mp4 path: iTunes `ilst`, no mdta box, no XMP.
    let f = generate(&dir, "plain.mp4", &["-metadata", "title=Plain"]);
    let edits = staged(&[("origin", "Camera"), ("location_place", "Coro Hotel")]);

    let (_, r) = write_it(&f, &edits, false);
    r.expect("the write must succeed");

    let got = probe::probe(&f).unwrap();
    assert_eq!(text(&got, "origin"), Some("Camera".into()));
    assert_eq!(
        got.lookup(field_by_id("location_place").unwrap()),
        Some(Value::text("Coro Hotel")),
        "the XMP half of the plan was dropped"
    );
}

/// The in-place writer is the one path that edits the original directly, so
/// its verification is the only thing standing between a declined XMP edit
/// and a "written" report. Both keys already exist on the file, which is
/// what routes the plan in place.
#[test]
fn an_in_place_write_verifies_its_xmp() {
    let dir = workspace("in-place-xmp");
    let f = tagged(&dir, "xmp.mp4");
    exiftool(&["-XMP-dc:Subject=old", "--", &f.to_string_lossy()]);

    let mut edits = BTreeMap::new();
    edits.insert(
        "tags".to_string(),
        Value::List(vec!["new".into(), "newer".into()]),
    );
    let (writer, r) = write_it(&f, &edits, false);
    r.expect("the write must succeed");
    assert_eq!(
        writer,
        Writer::Exiftool,
        "the fixture was meant to stay in place"
    );

    let got = probe::probe(&f).unwrap();
    assert_eq!(text(&got, "keywords"), Some("new, newer".into()));
    assert_eq!(
        got.xmp.get("XMP-dc:Subject"),
        Some(&Value::List(vec!["new".into(), "newer".into()])),
        "the XMP half of an in-place write was not written"
    );
}

/// A tag edit is not a modification of the footage, and a library sorted by
/// date-modified should not see one. Every writer promises this; for a long
/// while none delivered it, because `restore_mtime` set the file's mtime
/// from itself.
#[test]
fn the_mtime_survives_every_writer() {
    use std::time::{Duration, UNIX_EPOCH};
    let dir = workspace("mtime");
    let then = UNIX_EPOCH + Duration::from_secs(1_000_000_000);

    // In place: a key the file already has. Native: a key it does not.
    for (name, edits) in [
        ("in-place.mp4", staged(&[("title", "Updated")])),
        ("native.mp4", staged(&[("origin", "Camera")])),
    ] {
        let f = tagged(&dir, name);
        std::fs::File::options()
            .write(true)
            .open(&f)
            .unwrap()
            .set_modified(then)
            .unwrap();
        let (writer, r) = write_it(&f, &edits, false);
        r.expect("the write must succeed");
        let after = std::fs::metadata(&f).unwrap().modified().unwrap();
        assert_eq!(after, then, "{writer:?} bumped the mtime");
    }
}

// ---------------------------------------------------------------------------
// round-trips
// ---------------------------------------------------------------------------

/// Write every field the schema claims, read it back through both readers.
/// This is what turns the mapping table into something checked rather than
/// assumed -- a key ffmpeg or exiftool silently drops fails here.
#[test]
fn every_field_round_trips() {
    let dir = workspace("round-trip");
    let f = tagged(&dir, "all.mp4");

    // One field per container key. `actors` and `artist` both write `artist`
    // (DESIGN §17.4), and staging both would be asking for two values in one
    // key -- which is its own test, below.
    let mut claimed: Vec<&str> = Vec::new();
    let mut edits: BTreeMap<String, Value> = BTreeMap::new();
    let mut fields: Vec<&crate::model::schema::FieldDef> = Vec::new();
    for def in crate::model::schema::FIELDS
        .iter()
        .filter(|d| !d.mdta.is_empty())
    {
        if def.mdta.iter().any(|k| claimed.contains(k)) {
            continue;
        }
        claimed.extend(def.mdta.iter().copied());
        edits.insert(def.id.to_string(), Value::Text(format!("v-{}", def.id)));
        fields.push(def);
    }
    assert!(
        edits.len() > 10,
        "the schema should have plenty of mdta-backed fields"
    );

    let (_, r) = write_it(&f, &edits, false);
    r.expect("the write must succeed");

    let got = probe::probe(&f).unwrap();
    let mut missing: Vec<String> = Vec::new();
    for def in fields {
        let want = format!("v-{}", def.id);
        for key in def.mdta {
            if text(&got, key).as_deref() != Some(want.as_str()) {
                missing.push(format!("{key} = {:?}, wanted {want:?}", text(&got, key)));
            }
        }
    }
    assert!(
        missing.is_empty(),
        "keys did not round-trip:\n  {}",
        missing.join("\n  ")
    );
}

/// An emptied field must remove the key, not leave an empty one behind: an
/// empty string reads back as a present-but-blank value and shows in the form
/// as an edit that did nothing.
#[test]
fn an_emptied_field_removes_the_key() {
    let dir = workspace("delete");
    let f = tagged(&dir, "del.mp4");
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "title"),
        Some("Original".into())
    );

    let (_, r) = write_it(&f, &staged(&[("title", "")]), false);
    r.expect("the write must succeed");

    let got = probe::probe(&f).unwrap();
    assert_eq!(
        text(&got, "title"),
        None,
        "the key should be gone, not empty"
    );
    assert_eq!(
        text(&got, "category"),
        Some("Footage".into()),
        "a neighbour was lost"
    );
}

/// A clear is an edit like any other, and has to land on the XMP copy too:
/// XMP wins on read, so a title removed from the atom alone comes straight
/// back. The verify used to read the missing tag as one that "did not
/// survive", which failed every deletion on a file carrying XMP.
#[test]
fn an_emptied_field_removes_its_xmp_too() {
    let dir = workspace("delete-xmp");
    for (name, edits) in [
        ("text.mp4", staged(&[("title", "")])),
        (
            "list.mp4",
            BTreeMap::from([("tags".to_string(), Value::List(Vec::new()))]),
        ),
    ] {
        let f = tagged(&dir, name);
        exiftool(&[
            "-XMP-dc:Title=Original",
            "-XMP-dc:Subject=a",
            "-xmp:Rating=4",
            "--",
            &f.to_string_lossy(),
        ]);

        let (_, r) = write_it(&f, &edits, false);
        r.expect("the write must succeed");

        let got = probe::probe(&f).unwrap();
        let (key, tag) = if name == "text.mp4" {
            ("title", "XMP-dc:Title")
        } else {
            ("keywords", "XMP-dc:Subject")
        };
        assert_eq!(text(&got, key), None, "the key should be gone");
        assert_eq!(got.xmp.get(tag), None, "the XMP copy should be gone");
        assert_eq!(
            got.xmp.get("XMP-xmp:Rating"),
            Some(&Value::text("4")),
            "a neighbour was lost"
        );
    }
}

/// Unrecognised keys are never dropped (invariant 4): a key no field claims
/// has to survive a write aimed at a different field.
#[test]
fn a_key_no_field_claims_survives() {
    let dir = workspace("custom-key");
    let f = generate(
        &dir,
        "custom.mp4",
        &[
            "-movflags",
            "+use_metadata_tags",
            "-metadata",
            "title=Original",
            "-metadata",
            "sound_designer=Someone",
        ],
    );
    let (_, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    r.expect("the write must succeed");
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "sound_designer"),
        Some("Someone".into()),
        "a key the schema does not know was dropped"
    );
}

/// Two fields, one container key: `actors` and `artist` both write `artist`
/// (DESIGN §17.4). Setting them to different values cannot be honoured, and
/// what matters is that it **fails** rather than silently keeping whichever
/// value the plan happened to sort last.
///
/// Pinned rather than endorsed: if §17.4 is ever answered by making Artist
/// mirror Actors, this test is the one that should change.
#[test]
fn two_fields_writing_one_key_fail_rather_than_pick_a_winner() {
    let dir = workspace("collision");
    let f = tagged(&dir, "collide.mp4");
    let before = std::fs::read(&f).unwrap();

    let (_, r) = write_it(
        &f,
        &staged(&[("actors", "One, Two"), ("artist", "Someone Else")]),
        false,
    );

    assert!(r.is_err(), "two values for one key must not report success");
    assert!(
        r.unwrap_err().contains("did not round-trip"),
        "the verify is what catches this, and its message is what explains it"
    );
    assert_eq!(
        std::fs::read(&f).unwrap(),
        before,
        "a failed write changed the file"
    );
}

// ---------------------------------------------------------------------------
// tracks and layout
// ---------------------------------------------------------------------------

/// A second audio track and a timecode track both survive. The timecode track
/// is the one that made an early remux fail outright, and the second audio
/// track is the one a careless `-map 0:a` would silently drop.
#[test]
fn extra_tracks_survive_a_write() {
    let dir = workspace("tracks");
    let f = dir.join("two.mp4");
    let out = Command::new("ffmpeg")
        .args(["-hide_banner", "-loglevel", "error", "-nostdin", "-y"])
        .args(["-f", "lavfi", "-i", "testsrc=d=1:s=160x120"])
        .args(["-f", "lavfi", "-i", "sine=d=1"])
        .args(["-f", "lavfi", "-i", "sine=frequency=800:d=1"])
        .args(["-map", "0:v", "-map", "1:a", "-map", "2:a"])
        .args(["-c:v", "libx264", "-c:a", "aac"])
        .args(["-timecode", "01:00:00:00"])
        .args([
            "-movflags",
            "+use_metadata_tags",
            "-metadata",
            "title=Original",
        ])
        .arg("--")
        .arg(&f)
        .output()
        .expect("ffmpeg");
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );

    let before = write::probe_streams(&f);
    assert_eq!(before.len(), 4, "video, two audio, timecode");

    let (_, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    r.expect("the write must succeed");
    assert_eq!(
        write::probe_streams(&f),
        before,
        "a track changed across the write"
    );
}

/// A moov-at-end file is detected as such, and asking for faststart moves it.
#[test]
fn a_moov_at_end_file_is_detected_and_moved() {
    use crate::tags::atoms::{layout, Layout};
    let dir = workspace("faststart");
    let f = tagged(&dir, "slow.mp4");
    assert_eq!(
        layout(&f),
        Layout::MoovAtEnd,
        "ffmpeg's default should put moov last"
    );

    let (_, r) = write_it(&f, &staged(&[("title", "Updated")]), true);
    r.expect("the write must succeed");
    assert!(
        layout(&f).is_faststart(),
        "faststart was asked for and not delivered"
    );
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "title"),
        Some("Updated".into())
    );
}

/// A fragmented file is declined by the native writer rather than written with
/// offsets it cannot remap. Whether ffmpeg then manages it is a separate
/// question; what matters here is that the native path does not try.
#[test]
fn a_fragmented_file_is_declined_by_the_native_writer() {
    let dir = workspace("fragmented");
    let f = generate(
        &dir,
        "frag.mp4",
        &[
            "-movflags",
            "+use_metadata_tags+frag_keyframe+empty_moov",
            "-metadata",
            "title=Original",
        ],
    );
    assert!(
        crate::tags::native::survey(&f).unwrap().is_none(),
        "a fragmented file must be declined"
    );

    let tags = probe::probe(&f).unwrap();
    let plan = plan::build(&tags, &staged(&[("origin", "Camera")]), false);
    assert_ne!(
        plan.writer,
        Writer::Native,
        "routed to a writer that cannot handle it"
    );
}

// ---------------------------------------------------------------------------
// failure paths -- what matters is that the original is left alone
// ---------------------------------------------------------------------------

/// A file that cannot be replaced fails, and fails without damage. This is the
/// invariant the whole write path exists to keep: a failed write leaves the
/// original exactly as it was.
#[test]
fn a_read_only_directory_fails_and_leaves_the_original_alone() {
    use std::os::unix::fs::PermissionsExt;
    let dir = workspace("read-only");
    let f = tagged(&dir, "ro.mp4");
    let before = std::fs::read(&f).unwrap();

    let mut perms = std::fs::metadata(&dir).unwrap().permissions();
    perms.set_mode(0o500); // r-x: the file cannot be replaced
    std::fs::set_permissions(&dir, perms).unwrap();

    let (_, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);

    let mut perms = std::fs::metadata(&dir).unwrap().permissions();
    perms.set_mode(0o700);
    std::fs::set_permissions(&dir, perms).unwrap();

    assert!(r.is_err(), "a write into a read-only directory must fail");
    assert_eq!(
        std::fs::read(&f).unwrap(),
        before,
        "the original was modified by a failed write"
    );
}

/// A truncated file is not a container. Every path must refuse it rather than
/// produce a plausible-looking result from half an atom chain.
#[test]
fn a_truncated_file_is_refused() {
    let dir = workspace("truncated");
    let f = tagged(&dir, "cut.mp4");
    let whole = std::fs::read(&f).unwrap();
    std::fs::write(&f, &whole[..whole.len() / 2]).unwrap();
    let before = std::fs::read(&f).unwrap();

    // Probing may fail outright, which is a refusal too.
    if let Ok(tags) = probe::probe(&f) {
        let plan = plan::build(&tags, &staged(&[("origin", "Camera")]), false);
        let mut on = |_: write::Step| {};
        assert!(
            write::execute(&plan, &tags.xmp, &mut on).is_err(),
            "a truncated file must not write successfully"
        );
    }
    assert_eq!(
        std::fs::read(&f).unwrap(),
        before,
        "a refused write still changed the file"
    );
}

// ---------------------------------------------------------------------------
// the muxer is chosen, not inferred
// ---------------------------------------------------------------------------

/// `.m4v` is an mp4 file, but ffmpeg infers the `ipod` muxer from that name and
/// `ipod` has no tag for HEVC -- so an ordinary HEVC `.m4v` failed the remux
/// outright with "could not find tag for codec hevc". The remux names its
/// muxer now; this is that, end to end.
///
/// The fixture is generated as `.mp4` and renamed, because the generator would
/// hit the very same inference. Fragmented, so the native writer declines it
/// and the plan actually reaches ffmpeg.
#[test]
fn an_hevc_m4v_can_be_remuxed() {
    let dir = workspace("hevc-m4v");
    let src = generate(
        &dir,
        "hevc.mp4",
        &[
            "-c:v",
            "libx265",
            "-x265-params",
            "log-level=none",
            "-movflags",
            "+use_metadata_tags+frag_keyframe+empty_moov",
            "-metadata",
            "title=Original",
        ],
    );
    let f = dir.join("hevc.m4v");
    std::fs::rename(&src, &f).expect("renaming the fixture to .m4v");

    let (writer, r) = write_it(&f, &staged(&[("origin", "Camera")]), false);
    assert_ne!(
        writer,
        Writer::Native,
        "the fixture must reach ffmpeg to test anything"
    );
    r.expect("an HEVC .m4v must remux");
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "origin"),
        Some("Camera".into())
    );
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "title"),
        Some("Original".into())
    );
}

/// `.mov` is the one extension where the muxer is a real difference in what
/// gets written rather than a naming one (docs/CONTAINER.md §1.2), so it keeps
/// the mov muxer while everything else is mp4.
#[test]
fn only_mov_gets_the_mov_muxer() {
    for (name, want) in [
        ("a.mov", "mov"),
        ("a.QT", "mov"),
        ("a.mp4", "mp4"),
        ("a.m4v", "mp4"),
        ("a.M4V", "mp4"),
        ("a.m4a", "mp4"),
        ("a", "mp4"),
    ] {
        assert_eq!(write::muxer_for(Path::new(name)), want, "for {name}");
    }
}

// ---------------------------------------------------------------------------
// the capture time -- where a camera that is not an iPhone keeps it
// ---------------------------------------------------------------------------

/// An Android clip stores when it was shot only in `mvhd`, which ffprobe
/// reports as `creation_time`. The Date field must read it, and a remux must
/// hand it back: ffmpeg zeroes it when the key is cleared, and when it is not,
/// promotes it to an mdta key that reads as `X;X` and zeroes `mvhd` on the
/// *next* remux instead. Two writes in a row, so both halves are checked.
#[test]
fn a_cameras_creation_time_is_the_date_and_survives_a_remux() {
    let dir = workspace("creation-time");
    // No `use_metadata_tags`: the time lands in `mvhd` and nowhere else, as
    // a camera leaves it. No mdta box either, so the native writer declines
    // and the remux is the path taken.
    let path = generate(
        &dir,
        "cam.mp4",
        &["-metadata", "creation_time=2024-02-04T03:18:59Z"],
    );
    let date = field_by_id("date").unwrap();
    let shot = Value::text("2024-02-04T03:18:59.000000Z");
    let before = probe::probe(&path).unwrap();
    assert_eq!(
        before.lookup(date),
        Some(shot.clone()),
        "the Date field reads mvhd"
    );
    let t = atoms::times(&path).expect("a readable mvhd");
    assert_ne!(t.creation, 0);

    // A new key each round, so neither write can go in place. The first is
    // the remux; that gives the file an mdta box, so the native writer takes
    // the second and must leave `mvhd` alone rather than clear it as junk.
    for (round, key, value, writer) in [
        ("first", "title", "One", Writer::Ffmpeg),
        ("second", "genre", "Two", Writer::Native),
    ] {
        let (w, r) = write_it(&path, &staged(&[(key, value)]), false);
        assert_eq!(r, Ok(()), "{round} write");
        assert_eq!(w, writer, "{round} write took the expected path");
        assert_eq!(atoms::times(&path), Some(t), "{round} write kept mvhd");
        let after = probe::probe(&path).unwrap();
        assert_eq!(
            after.lookup(date),
            Some(shot.clone()),
            "{round} write: Date still reads"
        );
        assert_eq!(text(&after, key).as_deref(), Some(value));
        assert!(
            !text(&after, "creation_time")
                .unwrap_or_default()
                .contains(';'),
            "{round} write promoted creation_time into a second, accumulating copy"
        );
    }
}

// ---------------------------------------------------------------------------
// matroska -- §9.6
// ---------------------------------------------------------------------------

/// The original error, turned around: an `.mkv` with an attachment, which
/// the MP4 muxer cannot carry and the remux therefore choked on. Written
/// by the Matroska backend it keeps the attachment, the streams and the
/// tags no field claims.
fn matroska(dir: &Path, name: &str) -> PathBuf {
    let attachment = dir.join(format!("{name}.json"));
    std::fs::write(&attachment, br#"{"id": "fixture"}"#).unwrap();
    let a = attachment.to_string_lossy().into_owned();
    generate(
        dir,
        name,
        &[
            "-attach",
            &a,
            "-metadata:s:t",
            "mimetype=application/json",
            "-metadata",
            "title=Original",
            "-metadata",
            "category=Footage",
            "-metadata",
            "purl=https://example.com/a",
            "-metadata",
            "yt_dlp_id=12345",
        ],
    )
}

fn stream_kinds(path: &Path) -> Vec<String> {
    write::probe_streams(path)
        .iter()
        .map(|s| s.kind.clone())
        .collect()
}

fn ffprobe_tags(path: &Path) -> BTreeMap<String, Value> {
    probe::probe_atoms(path).expect("ffprobe on the fixture")
}

#[test]
fn a_matroska_file_is_read_and_written() {
    let dir = workspace("mkv");
    let f = matroska(&dir, "a.mkv");
    let kinds = stream_kinds(&f);
    assert!(kinds.contains(&"attachment".to_string()), "{kinds:?}");

    let before = probe::probe(&f).unwrap();
    assert_eq!(text(&before, "title").as_deref(), Some("Original"));
    assert_eq!(text(&before, "yt_dlp_id").as_deref(), Some("12345"));
    assert!(
        text(&before, "encoder").is_none(),
        "muxer bookkeeping is not shown"
    );
    let url = field_by_id("url").unwrap();
    assert_eq!(
        before.lookup(url),
        Some(Value::text("https://example.com/a"))
    );

    let edits = staged(&[
        ("title", "A new title, longer than the old one"),
        ("url", "https://example.com/b"),
        ("genre", "Test"),
        ("location", "Lisbon"),
        ("custom:yt_dlp_id", "67890"),
    ]);
    let (writer, r) = write_it(&f, &edits, true);
    assert_eq!(writer, Writer::Matroska);
    r.expect("the write");

    let after = probe::probe(&f).unwrap();
    assert_eq!(
        text(&after, "title").as_deref(),
        Some("A new title, longer than the old one")
    );
    assert_eq!(
        after.lookup(url),
        Some(Value::text("https://example.com/b"))
    );
    assert_eq!(text(&after, "genre").as_deref(), Some("Test"));
    assert_eq!(text(&after, "yt_dlp_id").as_deref(), Some("67890"));
    assert_eq!(
        text(&after, "category").as_deref(),
        Some("Footage"),
        "untouched"
    );
    let city = field_by_id("location").unwrap();
    assert_eq!(after.lookup(city), Some(Value::text("Lisbon")));
    assert_eq!(stream_kinds(&f), kinds, "the attachment is still there");

    // Every key the URL field fans out to, as an independent reader sees them.
    let seen = ffprobe_tags(&f);
    for key in url.mdta {
        assert_eq!(
            seen.get(*key),
            Some(&Value::text("https://example.com/b")),
            "{key}"
        );
    }
    assert_eq!(
        seen.get("title"),
        Some(&Value::text("A new title, longer than the old one"))
    );

    // Padded by the first write, so the second costs nothing and moves nothing.
    let mkv = fastmkv::open(&f).unwrap();
    assert!(mkv.seating().front);
    assert!(mkv.seating().tags_padding > 1024);
    let size = std::fs::metadata(&f).unwrap().len();
    let (_, r) = write_it(&f, &staged(&[("synopsis", "Something added later")]), true);
    r.expect("the second write");
    assert_eq!(std::fs::metadata(&f).unwrap().len(), size);
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "synopsis").as_deref(),
        Some("Something added later")
    );
}

/// One title, in one place: a file that arrives with a `TITLE` tag as well
/// leaves without it, because mpv shows both.
#[test]
fn a_matroska_title_is_written_once() {
    let dir = workspace("mkv-title");
    let f = matroska(&dir, "t.mkv");
    let mut mkv = fastmkv::open(&f).unwrap();
    mkv.set("Title", "a tag, and a stale one").unwrap();
    mkv.plan().unwrap().apply().unwrap();

    // Info wins while both are there.
    let both = probe::probe(&f).unwrap();
    assert_eq!(text(&both, "title").as_deref(), Some("Original"));

    let (_, r) = write_it(&f, &staged(&[("title", "The one title")]), false);
    r.expect("the write");
    let mkv = fastmkv::open(&f).unwrap();
    assert_eq!(mkv.title().as_deref(), Some("The one title"));
    assert!(mkv.global().all(|(n, _)| !n.eq_ignore_ascii_case("title")));

    // Cleared, it is gone from both.
    let (_, r) = write_it(&f, &staged(&[("title", "")]), false);
    r.expect("clearing");
    assert!(text(&probe::probe(&f).unwrap(), "title").is_none());
}

/// Spellings that differ only in case are one key: the last is shown, and
/// a write leaves one.
#[test]
fn matroska_spellings_of_one_key_are_collapsed() {
    let dir = workspace("mkv-case");
    let f = matroska(&dir, "c.mkv");
    let mut mkv = fastmkv::open(&f).unwrap();
    mkv.set("Genre", "first").unwrap();
    mkv.set("genre", "last").unwrap();
    mkv.plan().unwrap().apply().unwrap();
    assert_eq!(
        text(&probe::probe(&f).unwrap(), "genre").as_deref(),
        Some("last")
    );

    let (_, r) = write_it(&f, &staged(&[("genre", "only")]), false);
    r.expect("the write");
    let mkv = fastmkv::open(&f).unwrap();
    let genres: Vec<_> = mkv
        .global()
        .filter(|(n, _)| n.eq_ignore_ascii_case("genre"))
        .collect();
    assert_eq!(genres, vec![("genre", "only")], "under the spelling it had");
}

/// With the switch off a write is an update: the file is not copied, and
/// tags that outgrow their place go to the end.
#[test]
fn matroska_without_padding_updates_in_place() {
    let dir = workspace("mkv-nopad");
    let f = matroska(&dir, "n.mkv");
    let (_, r) = write_it(&f, &staged(&[("synopsis", &"grown ".repeat(50))]), false);
    r.expect("the write");
    let mkv = fastmkv::open(&f).unwrap();
    assert!(!mkv.seating().front, "sent to the end, not re-seated");
    assert_eq!(mkv.seating().tags_padding, 0);
}

/// A stream capture has no sizes. It is shown, and a write to it fails
/// with the reason and leaves it alone.
#[test]
fn a_matroska_file_that_cannot_be_edited_is_left_alone() {
    let dir = workspace("mkv-live");
    let f = matroska(&dir, "l.mkv");
    let live = dir.join("live.mkv");
    let out = Command::new("ffmpeg")
        .args(["-hide_banner", "-loglevel", "error", "-nostdin", "-y", "-i"])
        .arg(&f)
        .args([
            "-map", "0:v", "-map", "0:a", "-c", "copy", "-live", "1", "-f", "matroska", "--",
        ])
        .arg(&live)
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let bytes = std::fs::read(&live).unwrap();

    let tags = probe::probe(&live).expect("it is still read");
    assert_eq!(text(&tags, "category").as_deref(), Some("Footage"));
    let (_, r) = write_it(&live, &staged(&[("genre", "Test")]), true);
    let e = r.expect_err("it cannot be written");
    assert!(e.contains("unknown size"), "{e}");
    assert_eq!(std::fs::read(&live).unwrap(), bytes);
}

/// mkvmerge lays a file out differently from ffmpeg -- tags after the
/// clusters, no checksums, statistics aimed at each track -- and
/// mkvpropedit leaves an index split in two. Skipped without MKVToolNix.
fn mkvtoolnix(dir: &Path, name: &str) -> Option<PathBuf> {
    let src = tagged(dir, &format!("{name}.mp4"));
    let out = dir.join(name);
    let made = Command::new("mkvmerge")
        .args(["-q", "-o"])
        .arg(&out)
        .args(["--title", "Original"])
        .arg(&src)
        .status();
    match made {
        Ok(s) if s.success() => Some(out),
        _ => {
            eprintln!("mkvmerge not available; skipped");
            None
        }
    }
}

#[test]
fn a_file_from_mkvmerge_is_written() {
    let dir = workspace("mkvmerge");
    let Some(f) = mkvtoolnix(&dir, "m.mkv") else {
        return;
    };
    let kinds = stream_kinds(&f);

    let before = probe::probe(&f).unwrap();
    assert_eq!(text(&before, "title").as_deref(), Some("Original"));
    assert!(
        text(&before, "bps").is_none(),
        "a track's statistics are not the file's"
    );

    let (writer, r) = write_it(
        &f,
        &staged(&[("title", "Changed"), ("genre", "Test")]),
        true,
    );
    assert_eq!(writer, Writer::Matroska);
    r.expect("the write");
    let after = probe::probe(&f).unwrap();
    assert_eq!(text(&after, "title").as_deref(), Some("Changed"));
    assert_eq!(text(&after, "genre").as_deref(), Some("Test"));
    assert_eq!(stream_kinds(&f), kinds);

    let mkv = fastmkv::open(&f).unwrap();
    assert!(
        mkv.seating().front,
        "re-seated: mkvmerge had them at the end"
    );
    let of_tracks = mkv
        .tags
        .iter()
        .flat_map(|t| t.tags.tags())
        .filter(|t| !t.is_global())
        .count();
    assert_eq!(of_tracks, 2, "the statistics came through");
    let seen = Command::new("mkvmerge").arg("-J").arg(&f).output().unwrap();
    let seen: String = String::from_utf8_lossy(&seen.stdout)
        .split_whitespace()
        .collect();
    assert!(
        seen.contains("\"errors\":[]") && seen.contains("\"warnings\":[]"),
        "{seen}"
    );
    assert!(seen.contains("\"title\":\"Changed\""), "{seen}");
}

/// mkvpropedit rearranges a file as it edits: it moves the tags to the
/// end and `Info` into whatever padding it finds. Whatever shape it leaves,
/// the next write here reads the same values and puts the file back in
/// order. (The case where it splits the index in two depends on how much
/// room it finds, and is pinned down in fastmkv's own suite.)
#[test]
fn a_file_mkvpropedit_has_edited_is_written() {
    let dir = workspace("propedit");
    let Some(f) = mkvtoolnix(&dir, "p.mkv") else {
        return;
    };
    let (_, r) = write_it(&f, &staged(&[("genre", "Test")]), true);
    r.expect("seating it");
    let edit = |args: &[&str]| {
        let s = Command::new("mkvpropedit")
            .arg("-q")
            .arg(&f)
            .args(args)
            .status();
        assert!(s.is_ok_and(|s| s.success()));
    };
    let long = format!("title={}", "longer ".repeat(120));
    edit(&["--edit", "info", "--set", &long]);
    edit(&["--add-track-statistics-tags"]);
    assert!(
        !fastmkv::open(&f).unwrap().seating().front,
        "mkvpropedit is expected to have moved the tags"
    );

    let tags = probe::probe(&f).unwrap();
    assert_eq!(text(&tags, "genre").as_deref(), Some("Test"));
    assert!(text(&tags, "title").is_some_and(|t| t.starts_with("longer longer")));
    let kinds = stream_kinds(&f);

    let (_, r) = write_it(&f, &staged(&[("synopsis", &"grown ".repeat(80))]), true);
    r.expect("the write");
    let mkv = fastmkv::open(&f).unwrap();
    assert_eq!(mkv.survey.seek_heads, 1);
    assert!(mkv.seating().front);
    let after = probe::probe(&f).unwrap();
    assert_eq!(text(&after, "genre").as_deref(), Some("Test"));
    assert!(text(&after, "title").is_some_and(|t| t.starts_with("longer longer")));
    assert_eq!(text(&after, "synopsis").map(|s| s.len()), Some(6 * 80));
    assert_eq!(stream_kinds(&f), kinds);
}

// ---------------------------------------------------------------------------
// to matroska -- §9.7
// ---------------------------------------------------------------------------

fn codecs(path: &Path) -> Vec<(String, Option<String>)> {
    let mut v: Vec<_> = write::probe_streams(path)
        .into_iter()
        .map(|s| (s.kind, s.codec))
        .collect();
    v.sort();
    v
}

/// The values arrive whichever place the source kept them in -- an atom,
/// or XMP that ffmpeg cannot even see -- and the file that results is one
/// the Matroska backend would have left the same way.
#[test]
fn an_mp4_becomes_a_matroska_file() {
    let dir = workspace("convert");
    let f = generate(
        &dir,
        "c.mp4",
        &[
            "-movflags",
            "+use_metadata_tags",
            "-metadata",
            "title=Original",
            "-metadata",
            "category=Footage",
            "-metadata",
            "purl=https://example.com/a",
            "-metadata",
            "yt_dlp_id=12345",
        ],
    );
    let p = f.to_string_lossy().into_owned();
    exiftool(&[
        "-XMP-iptcExt:PersonInImage=Person One",
        "-XMP-iptcExt:PersonInImage=Person Two",
        "-xmp:Rating=4",
        "-XMP-iptcExt:LocationCreatedCity=Lisbon",
        &p,
    ]);
    let source = std::fs::read(&f).unwrap();

    let o = crate::convert::convert(&f, false, false).expect("the conversion");
    assert_eq!(o.dest, dir.join("c.mkv"));
    assert!(o.lost.is_empty(), "{:?}", o.lost);
    assert_eq!(
        std::fs::read(&f).unwrap(),
        source,
        "the source is only read"
    );

    assert!(crate::tags::mkv::is_matroska(&o.dest));
    assert_eq!(codecs(&o.dest), codecs(&f));
    let got = probe::probe(&o.dest).unwrap();
    let value = |id: &str| got.lookup(field_by_id(id).unwrap());
    assert_eq!(value("title"), Some(Value::text("Original")));
    assert_eq!(value("category"), Some(Value::text("Footage")));
    assert_eq!(value("url"), Some(Value::text("https://example.com/a")));
    assert_eq!(value("rating"), Some(Value::text("4")));
    assert_eq!(value("location"), Some(Value::text("Lisbon")));
    assert_eq!(
        value("actors"),
        Some(Value::List(vec!["Person One".into(), "Person Two".into()]))
    );
    assert_eq!(text(&got, "yt_dlp_id").as_deref(), Some("12345"));

    let mkv = fastmkv::open(&o.dest).unwrap();
    assert_eq!(mkv.title().as_deref(), Some("Original"));
    assert!(
        mkv.global().all(|(n, _)| !n.eq_ignore_ascii_case("title")),
        "one title"
    );
    assert!(
        mkv.global()
            .all(|(n, _)| !n.eq_ignore_ascii_case("major_brand")),
        "none of the muxer's bookkeeping"
    );
    assert!(mkv.seating().front);
    assert!(mkv.seating().tags_padding > 1024, "room to edit");

    // Nothing is left beside it, and it is not made twice.
    let strays: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with('.'))
        .collect();
    assert!(strays.is_empty(), "{strays:?}");
    let again = crate::convert::convert(&f, false, false)
        .unwrap_err()
        .to_string();
    assert!(again.contains("already exists"), "{again}");
}

/// What a Matroska file cannot hold is said, and is a refusal until the
/// loss is accepted.
#[test]
fn a_conversion_that_would_lose_something_is_refused() {
    let dir = workspace("convert-lossy");
    let f = tagged(&dir, "l.mp4");
    let p = f.to_string_lossy().into_owned();
    exiftool(&["-XMP-dc:Rights=All of them", &p]);

    let e = crate::convert::convert(&f, false, false)
        .unwrap_err()
        .to_string();
    assert!(e.contains("XMP-dc:Rights"), "{e}");
    assert!(!dir.join("l.mkv").exists());

    let dry = crate::convert::convert(&f, true, true).expect("a dry run");
    assert_eq!(dry.lost, vec!["XMP tag XMP-dc:Rights".to_string()]);
    assert!(!dir.join("l.mkv").exists(), "a dry run writes nothing");

    let o = crate::convert::convert(&f, true, false).expect("with the loss accepted");
    assert_eq!(o.lost.len(), 1);
    let got = probe::probe(&o.dest).unwrap();
    assert_eq!(text(&got, "title").as_deref(), Some("Original"));
}

#[test]
fn a_matroska_file_is_not_converted_to_itself() {
    let dir = workspace("convert-mkv");
    let f = matroska(&dir, "m.mkv");
    let e = crate::convert::convert(&f, true, false)
        .unwrap_err()
        .to_string();
    assert!(e.contains("already a Matroska file"), "{e}");
}
